# Deploy n8n on a free Render web service with Render Postgres.
services:
  - type: web
    plan: free
    runtime: image
    name: n8n-service
    image:
      url: docker.io/n8nio/n8n:latest
    envVars:
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: NODE_OPTIONS
        value: --max-old-space-size=384
      - key: N8N_RUNNERS_ENABLED
        value: false
      - key: PORT
        value: 5678
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_DATABASE
        value: postgres
      - key: DB_POSTGRESDB_HOST
        value: aws-0-ap-northeast-1.pooler.supabase.com
      - key: DB_POSTGRESDB_PORT
        value: 5432
      - key: DB_POSTGRESDB_PASSWORD
        sync: false
      - key: DB_POSTGRESDB_USER
        value: postgres.yrfqnhizntmateqwbvnp
      - key: DB_POSTGRESDB_SSL_ENABLED
        value: true      
      - key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
        value: false

databases:
  - name: n8n-db
    plan: free
